[project]
name = "q2d-dataset"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "httpx",
    "mcp[cli]",
    "requests",
]

[tool.uv]
virtualenvs.in-project = true
